FROM node:20-alpine AS build
RUN apk add --no-cache libc6-compat
WORKDIR /app

COPY package.json package-lock.json ./
COPY apps/web/package.json apps/web/package.json
COPY apps/api/package.json apps/api/package.json
COPY apps/worker/package.json apps/worker/package.json
COPY packages/db/package.json packages/db/package.json
COPY packages/core/package.json packages/core/package.json
COPY packages/ui/package.json packages/ui/package.json
RUN npm ci

COPY . .
RUN npm run db:generate
RUN npm --workspace @ori-os/db run build
RUN npm --workspace @ori-os/core run build
RUN npm --workspace @ori-os/worker run build

FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production

RUN addgroup --system --gid 1001 nodejs && adduser --system --uid 1001 nestjs
COPY --from=build --chown=nestjs:nodejs /app/apps/worker/dist ./dist
COPY --from=build --chown=nestjs:nodejs /app/node_modules ./node_modules
COPY --from=build --chown=nestjs:nodejs /app/apps/worker/package.json ./package.json
COPY --from=build --chown=nestjs:nodejs /app/packages ./packages

USER nestjs
CMD ["node", "dist/main.js"]
